Added the necessary srdf elements to disable collisions with base_link
neobotix/neo_mpo_moveit2 pull request #8
Opened 2024-11-28 08:25 UTC by AdarshKaran

Changed the srdf files to include relevant <disable_collision> tags
[Issue 103](https://github.com/neobotix/neo_simulation2/issues/103)

2024-11-29 09:23 UTC, padhupradheep requested changes

2024-11-29 09:23 UTC, padhupradheep commented on neo_ur_moveit_config/srdf/mpo_700.srdf.xacro
> +        <joint name="${prefix_value}elbow_joint" value="0" />
are those additional indentation?

2024-12-05 06:40 UTC, AdarshKaran commented on neo_ur_moveit_config/srdf/mpo_700.srdf.xacro
> +        <joint name="${prefix_value}elbow_joint" value="0" />
Yes Pradheep

2024-12-05 06:40 UTC, AdarshKaran commented on neo_ur_moveit_config/srdf/mpo_700.srdf.xacro
> +        <disable_collisions link1="docking_adapter_link" link2="lidar_1_link" reason="Never"/>
I have updated it to ensure consistent indentations now.

2025-04-17 11:12 UTC, padhupradheep commented
@AdarshKaran: can we close this PR then? It is not valid any more I think?

2025-04-17 11:40 UTC, AdarshKaran commented
Yes Pradheep. These changes are not required anymore.

2025-04-24 11:12 UTC, closed without merging